version: '3.41'

tasks:
  build-linux:
    cmds:
      - cmake . -B build && make -C build && ./build/lab6
  build-windows:
    cmds:
      - cmake . -B build -G "MinGW Makefiles" && cmake --build build && ./build/lab6
